apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  aws-access-key-id: QUtJQVU2R0RaTklISEtOUVo2V0I=
  aws-secret-access-key: U1JwalFwOUh1d0Q1MzZEZTBLWnNqOTNoL1hQSVlFYVhhcGt1WFJKdA==